
import React from "react";
// import { usePDF } from "react-to-pdf";
import { KPIBlock, type KPIResult } from "./KPIBlock";

interface ReportPDFProps {
    reportContent: string;
    kpis: KPIResult[];
    title?: string;
    date?: string;
}

export const ReportPDF = React.forwardRef<HTMLDivElement, ReportPDFProps>(
    ({ reportContent, kpis, title = "Safety Analysis Report", date = new Date().toLocaleDateString() }, ref) => {

        return (
            <div ref={ref} className="p-8 bg-white text-slate-900 min-h-screen">
                {/* Header */}
                <div className="border-b border-slate-200 pb-4 mb-8">
                    <div className="flex justify-between items-center">
                        <div>
                            <h1 className="text-2xl font-bold text-[#0B3D91]">{title}</h1>
                            <p className="text-sm text-slate-500">Generated on {date}</p>
                        </div>
                        <div className="text-right">
                            <span className="text-xs font-semibold px-2 py-1 bg-blue-50 text-blue-700 rounded">
                                DATTU AI GENERATED
                            </span>
                        </div>
                    </div>
                </div>

                {/* Verified KPIs Section */}
                {kpis && kpis.length > 0 && (
                    <div className="mb-8">
                        <h2 className="text-lg font-semibold text-slate-800 mb-4 border-l-4 border-green-500 pl-3">
                            Verified Key Performance Indicators
                        </h2>
                        <div className="space-y-4">
                            {/* We reuse KPIBlock but might want a simpler layout for PDF if KPIBlock is too interactive/card-heavy. 
                   However, reuse is good for consistency. 
                   Let's assume KPIBlock renders fine. We might need to adjust widths.
               */}
                            <KPIBlock kpis={kpis} title="" />
                        </div>
                    </div>
                )}

                {/* AI Report Content */}
                <div className="prose prose-slate max-w-none">
                    <h2 className="text-lg font-semibold text-slate-800 mb-4 border-l-4 border-[#0B3D91] pl-3">
                        AI Analysis & Insights
                    </h2>
                    <div
                        dangerouslySetInnerHTML={{ __html: reportContent }}
                        className="text-sm leading-relaxed"
                    />
                </div>

                {/* Footer */}
                <div className="mt-12 pt-4 border-t border-slate-200 text-center text-xs text-slate-400">
                    <p>Generated by DATTU Safety Intelligence Platform • Confidential</p>
                </div>
            </div>
        );
    }
);

ReportPDF.displayName = "ReportPDF";
